# learning_rate
learning_rate: 0.001
# reduction parameter
reduction_parameter: 0.6
# train epochs
epochs: 30
# Sequence Length
sequence_length: 48
# Batch size
batch_size: 32
# ORT_MIT_LOSS parameter
loss_parameter: 2
# checkpoints paths
models_path: "./trained_models/convAE"
