# learning_rate
learning_rate: 0.000007
# reduction parameter
reduction_parameter: 0.7
# train epochs
epochs: 2 #30
# Sequence Length
sequence_length: 12
# Batch size
batch_size: 16
# ORT_MIT_LOSS parameter
loss_parameter: 0.5
# checkpoints paths
models_path: "./trained_models/LSTM_AE"
