# learning_rate
learning_rate: 0.26
# reduction parameter
reduction_parameter: 0.5
# train epochs
epochs: 70
# Sequence Length
sequence_length: 24
# Batch size
batch_size: 32
# ORT_MIT_LOSS parameter
loss_parameter: 0.5
# checkpoints paths
models_path: "./trained_models/AE"
