# learning_rate
learning_rate: 0.002
# reduction parameter
reduction_parameter: 0.6
# train epochs
epochs: 2 #50
# Sequence Length
sequence_length: 36
# Batch size
batch_size: 16
# ORT_MIT_LOSS parameter
loss_parameter: 0.5
# checkpoints paths
models_path: "./trained_models/convAE"
