# learning_rate
learning_rate: 0.0001
# reduction parameter
reduction_parameter: 0.7
# train epochs
epochs: 30
# Sequence Length
sequence_length: 24
# Batch size
batch_size: 32
# ORT_MIT_LOSS parameter
loss_parameter: 8
# checkpoints paths
models_path: "./trained_models/LSTM_AE"
