# learning_rate
learning_rate: 0.001
# reduction parameter
reduction_parameter: 0.9
# train epochs
epochs: 30
# Sequence Length
sequence_length: 12
# Batch size
batch_size: 16
# ORT_MIT_LOSS parameter
loss_parameter: 0.5
# checkpoints paths
models_path: "./trained_models/convAE"
